# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('uuid', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('secret', models.CharField(max_length=16)),
                ('task_type', models.CharField(max_length=16)),
                ('adjective', models.CharField(blank=True, max_length=16, null=True)),
                ('noun', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
    ]
