# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw_captcha', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='draw_captcha/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adjective', models.CharField(max_length=16)),
                ('noun', models.CharField(max_length=16)),
                ('valid_identifications', models.PositiveIntegerField(default=0)),
                ('failed_identifications', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
