# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw_captcha', '0002_pictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='invalid_pictures',
            field=models.ManyToManyField(related_name='invalid_in_tasks', to='draw_captcha.Picture'),
        ),
        migrations.AddField(
            model_name='task',
            name='valid_pictures',
            field=models.ManyToManyField(related_name='valid_in_tasks', to='draw_captcha.Picture'),
        ),
        migrations.AlterField(
            model_name='task',
            name='secret',
            field=models.CharField(blank=True, default=None, max_length=16, null=True, unique=True),
        ),
    ]
